#!/bin/bash
logfile="BashLog"
log() {
 tee -a "$logfile"
}

while [ -n "$1" ]
 do
  case "$1" in
   -d) path="$2"
   shift;;
   --) shift
   break;;
   *) echo "$1 is not an option" | log;;
  esac
 shift
done

while [[ $path = "" ]]; do
 echo "Root path is empty, write the path" | log
 read path
done
echo "Root path is $path" | tee BashLog
getent passwd | while IFS=: read -r name password uid gid gecos home shell; do
 mkdir -pm 755 "$path/$name"
 chown "$uid:$gid" "$path/$name"
 echo "Created $path/$name directory with $uid:$gid ownership" | log
done
